remote_url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTbW2Id1vFUzhV_oIIWvPBJ24MI1i6qumRLDZObuwg-rfWY6nsQ_3nKSeavGjiKmlyDFMctjgVUiYe_/pub?output=csv'
proj_dir:  'C:\Users\ka003737\Downloads\Spring_2023\GIS3005\Lab1\Katie_McDaniel_Lab1\WestNileOutbreak'
data_format: 'GSheet'
geocoder_prefix_url: 'https://geocoding.geo.census.gov/geocoder/locations/onelineaddress?address='
geocoder_suffix_url: '&benchmark=2020&format=json'
#Push



